services:
  - type: web
    name: esquinabaja-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && curl -L -o yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp && chmod +x yt-dlp
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: IG_COOKIES_TXT
        sync: false
